### ISSUE TITLE
Action <-> SDK doesn't send

### ISSUE THREAD

**Issue by Bastiti** [spdermn02/touchportal-node-api#10]
From the log.txt:
Seems Touch Portal get the request.
![image](https://user-images.githubusercontent.com/37415063/151444398-48de6a13-3cf5-46a1-a7ee-2d387b8a3a87.png)

`TPClient.on("Action", (data, isHeld) => {
  console.log(JSON.stringify(data));
});
`

And here's the logs from my nodejs program.
![image](https://user-images.githubusercontent.com/37415063/151444708-e5321ab0-1d7c-4d17-88fe-e185188aa870.png)

Thanks in advance.

**Comment by Bastiti** [comment]
PS: Hours seems to be UTC on the JS applications. 
And GMT+1 on TouchPortal

**Comment by spdermn02** [comment]
can you provide your entry.tp file as well? My guess is your action isn't defined as a communicate type action.
