### ISSUE TITLE
Implement Connector ShortIds

### ISSUE THREAD

**Issue by Pjiesco** [spdermn02/touchportal-node-api#11]
In the new api (V5) there is a shortId added to connectors to be able to avoid the 200 character limit when updating connectors.
[Doc](https://www.touch-portal.com/api/index.php?section=connectors)

example message that gets send:
```json
{
  "type":"shortConnectorIdNotification",
  "pluginId":"id of the plugin",
  "shortId":"shortid of the connector",
  "connectorId":"the long normal connector id"
}
```

**Comment by spdermn02** [comment]
Thanks for adding - it's probably less of an issue since this doesn't auto generate those long id's like the Java SDK, but definitely to be fully up to date on newest TP SDK it needs to be added.
