### ISSUE TITLE
Unable to connect 127.0.0.1:12136

### ISSUE THREAD

**Issue by oozman** [spdermn02/touchportal-node-api#4]
Tried your sample code in docs. But unfortunately i can't make it work. 

Am i missing something?

Thanks

**Comment by spdermn02** [comment]
Do you have Touch Portal running? Also if you previously haven't had a plugin installed the plugin side of Touch Portal isn't running. So you would need to install one, and fully close (using system tray) and then start it again.

**Comment by spdermn02** [comment]
One thing to note is that Touch Portal Pro is required for plugins. Feel free to open a new ticket if there is still an issue.
